### ISSUE TITLE
Empty data set in different positions

### ISSUE THREAD

**Issue by pawelkata** [dzenbot/DZNEmptyDataSet#11]
Hi,

I'm having a very strange problem: the empty data set moves to a different position after some data have been available for a controller and then were removed.

The screenshot below shows what I have in mind:

![dzn-error](https://cloud.githubusercontent.com/assets/962904/3439333/dcadac1e-00e2-11e4-94c4-4e09ac069fc9.jpg)

The empty data set first appears as on the left screenshot. Then, after adding and deleting some data it appears as on the right screenshot.

I do reload the view in viewWillAppear.

This is only a minor issue but do you have any ideas on why this might be happening?

Cheers,

Pawel

**Comment by guilhermearaujo** [comment]
I am still facing this misalignment problem:

![error](http://cl.ly/image/2p2n1l0R3s0X/Image%202015-04-01%20at%207.00.30%20PM.png)

I included the library via CocoaPods: `pod 'DZNEmptyDataSet', '~> 1.5.2'`

**Comment by guilhermearaujo** [comment]
I noticed that the label appears in the correct position at first, but if I call `reloadEmptyDataSet` it changes. I am calling that method to update the string from "Loading" to a message saying there is no content to be show. I suppose that is the correct way to refresh the text, right?

**Comment by alex4814** [comment]
Using code
```swift
override func viewDidLayoutSubviews() {
    super.viewDidLayoutSubviews()
    
    if collectionView?.emptyDataSetSource == nil {
        collectionView?.emptyDataSetSource = self
        collectionView?.reloadEmptyDataSet()
    }
}
```
correctly places empty view in the vertical centre, however when I add a pull to refresh control [MJRefresh](https://github.com/CoderMJLee/MJRefresh), the refreshing header isn't visible while the empty view scrolls down as suggested in the second problem of issue #43.

I just invoke `collectionView?.header.beginRefreshing()` in `viewDidLoad()` method for initial data fetching.

Any suggestions for this problem?

**Comment by vishal91** [comment]
Created the view with snapkit. But it is terribly misplaced. How to resolve this. 
`    func offsetForEmptyDataSet(scrollView: UIScrollView!) -> CGPoint {
        let top = scrollView.contentInset.top/2
        let bottom = scrollView.contentInset.bottom/2
        return CGPoint(x: 0, y: top-bottom)
    }

    func customViewForEmptyDataSet(scrollView: UIScrollView!) -> UIView! {
        let view = TNYEmptyStateView(stateType: .NoData)
        return view
    }`

**Comment by vishal91** [comment]
Created the view with snapkit. But it is terribly misplaced. How to resolve this. 

```
    func offsetForEmptyDataSet(scrollView: UIScrollView!) -> CGPoint {
        let top = scrollView.contentInset.top/2
        let bottom = scrollView.contentInset.bottom/2
        return CGPoint(x: 0, y: top-bottom)
    }

    func customViewForEmptyDataSet(scrollView: UIScrollView!) -> UIView! {
        let view = TNYEmptyStateView(stateType: .NoOrder)
        return view
    }
```

**Comment by victorstewart** [comment]
I'm also having this problem still. Using the latest version on Pods.

**Comment by manicmaniac** [comment]
I'm facing the same problem.
My app has a collection view under a navigation bar with a search bar.

I tried this solution: https://github.com/dzenbot/DZNEmptyDataSet/issues/11#issuecomment-47973126
It works but shows misplaced views for a second.

Maybe a too primitive solution but the following works fine.

```
func verticalOffset(forEmptyDataset scrollView: UIScrollView!) -> CGFloat {
    return -64
}
```

**Comment by henning-jh** [comment]
Yup, I have this issue as well. FWIW, I have a toolbar underneath the navbar, and I am using a vertical offset to try to fix this problem, but it only works sometimes. If all items disappear from a table view and the emptydataset view appears, it's high. But if I create a new table view and it's empty right away, it's low.

**Comment by damiancesar** [comment]
@henning-jh I'm having the exact same issue. Were you able to figure it out?

**Comment by MojtabaHs** [comment]
You can use my branch https://github.com/MojtabaHs/DZNEmptyDataSet

**Comment by Fouda** [comment]
you need just to set this in the delegate:
