### ISSUE TITLE
DZNEmptyDataSetView is cover the tableHeaderView

### ISSUE THREAD

**Issue by crazy8** [dzenbot/DZNEmptyDataSet#111]
the DZNEmptyDataSetView's frame is equal to the tableView.bounds,so it cover the tableHeaderView, the situation is i have a large tableHeaderView and some buttons in it, and now i cannot receive the user interactive.
![image](https://cloud.githubusercontent.com/assets/6948906/9052849/2feb49a8-3a9f-11e5-9e62-9e936eada06e.png)

i try set the offset, it just move the customView.
maybe provide the delegate to set the DZNEmptyDataSetView's frame or origin is better .
Just a suggestion.

**Comment by nikhildcodalsystem** [comment]
change following code at - (void)dzn_reloadEmptyDataSet in UIScrollView + EmptyDataSet.m

            if (([self isKindOfClass:[UITableView class]] || [self isKindOfClass:[UICollectionView class]]) && self.subviews.count > 1) {
                [self insertSubview:view atIndex:1];
            }
            else {
                [self addSubview:view];
            }

With Following code

  if (([self isKindOfClass:[UITableView class]] || [self isKindOfClass:[UICollectionView class]]) && self.subviews.count > 1) {
                [self insertSubview:view atIndex:0];
            }
            else {
                [self addSubview:view];
            }

**Comment by natewang** [comment]
@dzenbot  if there is only one subview , empty view will add on it.  I think self.subviews.count should > 0
