### ISSUE TITLE
No touch events in custom view

### ISSUE THREAD

**Issue by Jameson-zxm** [dzenbot/DZNEmptyDataSet#130]
we need touch events in custom view.

**Comment by avdyushin** [comment]
There is no touches because of a bug in constraints.
Your custom view's height is equal to 0.
Quick fix inside your view's class:

```
- (CGSize)intrinsicContentSize
{
    return CGSizeMake(UIViewNoIntrinsicMetric, CGRectGetHeight([UIScreen mainScreen].bounds));
}
```
