### ISSUE TITLE
Other libraries conflict crash

### ISSUE THREAD

**Issue by Nihility-Ming** [dzenbot/DZNEmptyDataSet#131]
2015-09-07 14:52:59.623 ---[375:34114] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'An instance 0x15e1b2200 of class UITableView was deallocated while key value observers were still registered with it. Current observation info: <NSKeyValueObservationInfo 0x17024d200> (
<NSKeyValueObservance 0x1702dacc0: Observer: 0x15d6ec370, Key path: contentOffset, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x17024e190>
<NSKeyValueObservance 0x1702dad30: Observer: 0x15d6ec370, Key path: contentSize, Options: <New: YES, Old: YES, Prior: NO> Context: 0x0, Property: 0x17024d380>
)'
*** First throw call stack:
(0x186f8259c 0x1976e00e4 0x186f824dc 0x187dd9f00 0x186e61228 0x186e6d7e8 0x1976f9724 0x186e64e44 0x186f38054 0x186e650a4 0x1900075a4 0x18b79a3c0 0x1002b6d80 0x197d4ea08)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by Nihility-Ming** [comment]
May be related and `MJRefresh`, It also replaces(swizzle) the dealloc method.

**Comment by mythodeia** [comment]
@Nihility-Ming download the latest version and on your dealloc nullify like this:
```
self.tableView.emptyDataSetSource = nil;
self.tableView.emptyDataSetDelegate = nil;
``` 
or
```
self.collectionView.emptyDataSetSource = nil;
self.collectionView.emptyDataSetDelegate = nil;
```

**Comment by Nihility-Ming** [comment]
@mythodeia Thank you!
But, useless.

MJRefresh:

```Objective-C
+ (void)exchangeInstanceMethod1:(SEL)method1 method2:(SEL)method2
{
    method_exchangeImplementations(class_getInstanceMethod(self, method1), class_getInstanceMethod(self, method2));
}

+ (void)exchangeClassMethod1:(SEL)method1 method2:(SEL)method2
{
    method_exchangeImplementations(class_getClassMethod(self, method1), class_getClassMethod(self, method2));
}
```

and

```Objective-C
+ (void)load
{
    [self exchangeInstanceMethod1:@selector(reloadData) method2:@selector(mj_reloadData)];
    [self exchangeInstanceMethod1:@selector(reloadRowsAtIndexPaths:withRowAnimation:) method2:@selector(mj_reloadRowsAtIndexPaths:withRowAnimation:)];
    [self exchangeInstanceMethod1:@selector(deleteRowsAtIndexPaths:withRowAnimation:) method2:@selector(mj_deleteRowsAtIndexPaths:withRowAnimation:)];
    [self exchangeInstanceMethod1:@selector(insertRowsAtIndexPaths:withRowAnimation:) method2:@selector(mj_insertRowsAtIndexPaths:withRowAnimation:)];
    [self exchangeInstanceMethod1:@selector(reloadSections:withRowAnimation:) method2:@selector(mj_reloadSections:withRowAnimation:)];
    [self exchangeInstanceMethod1:@selector(deleteSections:withRowAnimation:) method2:@selector(mj_deleteSections:withRowAnimation:)];
    [self exchangeInstanceMethod1:@selector(insertSections:withRowAnimation:) method2:@selector(mj_insertSections:withRowAnimation:)];
}
```
