### ISSUE TITLE
Empty Data Display but also display the headerView 

### ISSUE THREAD

**Issue by kong707** [dzenbot/DZNEmptyDataSet#25]
Is it possible to use DZNEmptyDataSet to combine with UICollectionVC ?
I mean  my UICollectionVC always has a headerView like the profile page in Twitter. But sometimes the data set is zero and I would like to show a suggestion to user via DZNEmptyDataSet.   I already tried but the Empty Display just cover the whole view if data is zero even if I have headerView.  Are there any easy way to tweak the module to work that way? 

Thanks in advance

**Comment by JCCP3** [comment]
u can set your empty view's backgroundColor clearColor
