### ISSUE TITLE
Rotation Layout

### ISSUE THREAD

**Issue by mmorey** [dzenbot/DZNEmptyDataSet#31]
When rotating a `UITableView` that implements `DZNEmptyDataSet` the empty data set view does not adjust it's layout, see GIF:

![tableview_rotation_issue](https://cloud.githubusercontent.com/assets/251031/3892384/d9f5f268-2231-11e4-93b3-ab77c61dbd17.gif)

From the GIF you should be able to see 2 issues:
1. The text does not auto expand to fill the whole width of the screen when rotated to landscape.
2. The last line ("To clean the list, tap on the trash icon.") gets cut off when rotated to landscape.

If you add the following code to the Colors table example the issue is exacerbated:

``` objective-c
- (void)willRotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation duration:(NSTimeInterval)duration
{
    [self.tableView reloadData];
}
```

If instead you use `didRotateFromInterfaceOrientation` the view will layout properly but the animation is not very good.

``` objective-c
- (void)didRotateFromInterfaceOrientation:(UIInterfaceOrientation)fromInterfaceOrientation {

    [self.tableView reloadData];
}
```

Here is how the collection view behaves:

![collectionview_rotation_issue](https://cloud.githubusercontent.com/assets/251031/3892444/5fbbcdaa-2232-11e4-945a-f7ca132dd4d9.gif)

The animation behavior for the collection view is better although the last line is still cut off. The last line being cut off is not really an issues that can be solved without dynamically changing the placeholder image.

Any suggestions on how to make the rotation animation better with table views?

**Comment by pableiros** [comment]
I have the same problem, is there some way to solve that in swift with xcode 8? Because `didRotateFromInterfaceOrientation` is deprecated
