### ISSUE TITLE
weird issue when archiving for ad hoc deployment

### ISSUE THREAD

**Issue by Nathan187** [dzenbot/DZNEmptyDataSet#319]
came across this cool library and really want to use it, however i'm having the damnedest issue that has me pulling my hair out

previously, i have been able to create ipa(s) to distribute beta builds without a problem.  however when i drop this library/framework in...i get errors when i try to build the ipa.  i'm not sure if it's the library but when i roll back to previous commits (before using this library)...I have no issue.  the logs say something about certificate errors but i'm hoping it's just some random or wrong error message of some sort.  this happens on two separate macs

cartfile entry:  github "dzenbot/DZNEmptyDataSet"
command used to build frameworks:  carthage update --platform iOS --no-use-binaries
xcode version:  8.2.1
(updated ruby but I don't think this has anything to do with it)

thanks for any help in advance

**Comment by Nathan187** [comment]
bump

**Comment by Nathan187** [comment]
was able to fix / resolve the issue.  had nothing to do with this library

**Comment by Liaoworking** [comment]
same issue

**Comment by Nathan187** [comment]
@Liaoworking you probably figured this out already.  if i remember correctly....the issue i had was, in my project settings - build phases.....in the compile sources area...i had a file in there that didn't belong at all.  i don't know how it got there.  the compiler would stop and throw an error.  it was very misleading and it took a lot of digging through the logs to figure it out.  it may be a pain to look through the entirety of the logs but it really helped.  good luck
