### ISSUE TITLE
State for Loading.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [dzenbot/DZNEmptyDataSet#338]
Thanks for this wonderful library.

Can I show loading indicator while data is loading from the server?

**Comment by JoniVR** [comment]
Hi,
Yes, you can do this, the easiest way would be to use the `customViewForEmptyDataSet ` function.
Use a global boolean (for example isLoading) and in your function where you get the data from the server, when you start loading set it to true, then, when it's finished fetching, set the boolean to false, then run `tableview.reloadData()`

In your `customViewForEmptyDataSet`, you should check for "isLoading" if it is true, return a loading indicator, else just return nil :)

**Comment by Rashesh-Bosamiya** [comment]
Thanks for reply.

I will try this.
