### ISSUE TITLE
In swift project, Sometimes TableView's delegate method don't execute.

### ISSUE THREAD

**Issue by gyzerocc** [dzenbot/DZNEmptyDataSet#382]
**Sometimes but not every time.**

TableView's datasource isn't empty.
When exec tableView.reloadData()
TableView's delegate method
like
```
public func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int
public func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell
``` 
It's not called.

**Comment by gyzerocc** [comment]
No. It's in my swift project. Now I have removed it and use custom empty view. 
like this:
```
api.get { items, err in
    if err { ... return }
    emptyView.isHidden = !items.isEmpty
}
```
🤣 
It can be exec correctly.

**Comment by Liaoworking** [comment]
same issue..

**Comment by Liaoworking** [comment]
finally, I find it's a bug of XCode10.2. It's not caused by your framework. This is the bug report 
      https://forums.swift.org/t/xcode-10-2-protocol-inheritance-issue/22862
