### ISSUE TITLE
customView doesn't disappear after filling the CollectionView

### ISSUE THREAD

**Issue by Ivan-Cantarino** [dzenbot/DZNEmptyDataSet#394]
Hello.

I've used text placeholders before, while it was fetching data to fill the `UICollectionView` , but recently I have changed to the `customView` delegate method, in which I instantiate a `UIActivityIndicatorView`.

It starts spinning on launch/load, but after fetching the data and filling the `UICollectionView` that `UIActivityIndicatorView` doesn't disappear, it keeps on screen, but that didn't happened with the regular text before,

    func customView(forEmptyDataSet scrollView: UIScrollView!) -> UIView! {
		let activityIndicator = UIActivityIndicatorView(activityIndicatorStyle: .gray)
		activityIndicator.startAnimating()
		return activityIndicator
	}

any hint what may be causing this?

**Comment by beilusen** [comment]
请问如何解决的
