### ISSUE TITLE
Title won't change when other segment in UISegmentedControl is clicked 

### ISSUE THREAD

**Issue by devaileen** [dzenbot/DZNEmptyDataSet#402]
The title on the view doesn't change when one segment is selected. For example in the my code below:

        switch (mySegmentedControl.selectedSegmentIndex) {
        case 0:
            let text = "No books borrowed"
            return NSAttributedString(string: text)
        case 1:
            let text = "No books returned"
            return NSAttributedString(string: text)
        default:
            return NSAttributedString(string: "")
        }

but when I select the other segment, the title won't change. Is there any solution in this? Many thanks!

**Comment by iPhoNewsRO** [comment]
you need to `reloadData` on your table in order to change the text

**Comment by devaileen** [comment]
@iPhoNewsRO you mean inside each case?

**Comment by devaileen** [comment]
You're right! I must've forget to apply it in my code. Thank you so much @iPhoNewsRO 
Closing this now
