### ISSUE TITLE
- (UIView *)customViewForEmptyDataSet:(UIScrollView *)scrollView not work.

### ISSUE THREAD

**Issue by KeymonWong** [dzenbot/DZNEmptyDataSet#405]
自定义 view，不显示（即使设置了 frame），按钮不响应点击事件（原因是添加按钮的父view无大小）的分析：

原因是DZNEmptyDataSet的布局是autolayout（具体看DZNEmptyDataSet的 .m 文件），不是 frame 布局，所以自定义 view 时候，即使设置 frame，也不起作用，自定义的 view 没有尺寸，因此上面也不响应任何事件。

具体解决方法就是：

- (UIView *)customViewForEmptyDataSet:(UIScrollView *)scrollView {
//自定义的 view 用 autolayout 布局就可以了，我用的是 masonry
}

 from 每一个贡献了解决该方法的人员，thanks

**Comment by fanguohuiruan** [comment]
In line 928, it just add constraint for width not for height, you should add constraint for height . like this 
    [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|[contentView]|" options:0 metrics:nil views:@{@"contentView":self.contentView}]];

**Comment by bigNiuSanMao** [comment]
> 自定义 view，不显示（即使设置了 frame），按钮不响应点击事件（原因是添加按钮的父view无大小）的分析：
> 
> 原因是DZNEmptyDataSet的布局是autolayout（具体看DZNEmptyDataSet的 .m 文件），不是 frame 布局，所以自定义 view 时候，即使设置 frame，也不起作用，自定义的 view 没有尺寸，因此上面也不响应任何事件。
> 
> 具体解决方法就是：
> 
> * (UIView *)customViewForEmptyDataSet:(UIScrollView *)scrollView {
>   //自定义的 view 用 autolayout 布局就可以了，我用的是 masonry
>   }
> 
> from 每一个贡献了解决该方法的人员，thanks

自定义的view需要把视图 添加到哪个父视图上面？
