### ISSUE TITLE
解决自定义view时，点击控件无响应问题

### ISSUE THREAD

**Issue by Liyongcong** [dzenbot/DZNEmptyDataSet#437]
1.在setupConstraints添加
    //自己添加的，解决自定义view点击无响应问题
    if (_customView) {
        [self addConstraints:[NSLayoutConstraint constraintsWithVisualFormat:@"V:|[contentView]|" options:0 metrics:nil views:@{@"contentView": self.contentView}]];
    }
2.- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event
{
    UIView *hitView = [super hitTest:point withEvent:event];
    
    // Return any UIControl instance such as buttons, segmented controls, switches, etc.
    if ([hitView isKindOfClass:[UIControl class]]) {
        return hitView;
    }
    //自己添加的，解决自定义view点击无响应问题
    if (!_customView) {
        // Return either the contentView or customView
        if ([hitView isEqual:_contentView] || [hitView isEqual:_customView]) {
            return hitView;
        }
    }

    return nil;
}

**Comment by olderfe** [comment]
还是不行啊  快崩溃了

**Comment by iwantFB** [comment]
重写自定义视图的 intrinsicContentSize 方法
或者给自定义视图一个frame
