### ISSUE TITLE
自定义视图，点击按钮控件无反应

### ISSUE THREAD

**Issue by Link-Start** [dzenbot/DZNEmptyDataSet#441]
发现点击到的是 DZNEmptyDataSetView 无法点击到按钮  怎么解决

**Comment by Jyhwenchai** [comment]
1. 是否实现了 - (CGSize)intrinsicContentSize 
2. 检查下视图的布局中的按钮是否在自定义的视图frame范围内, 可以用 xcode 自带工具查看或者使用 reveal

**Comment by Link-Start** [comment]
多谢大哥，在自定义View中实现 - （CGSize）intrinsicContentSize   这个方法后，可以点击了，谢谢
