### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by mohammad19991** [dzenbot/DZNEmptyDataSet#445]
Add `Package.swift` to `DZNEmptyDataSet`

**Package Resolution Failed**
![image](https://user-images.githubusercontent.com/2028141/66455388-ae708f00-ea7b-11e9-95b8-1f17781a7f5f.png)

**Comment by kunalverma25** [comment]
@dzenbot  Added a PR to support SPM.
https://github.com/dzenbot/DZNEmptyDataSet/pull/447

**Comment by kunalverma25** [comment]
@mohammad19991 For now you can use the fork repo "https://github.com/kunalverma25/DZNEmptyDataSet" in SPM.
It works well in the meantime.

@dzenbot Can you check and merge the PR.

**Comment by mohammad19991** [comment]
thanks @kunalverma25
