### ISSUE TITLE
Gestures not reaching custom view in iOS7 when tableview has a background view

### ISSUE THREAD

**Issue by atetlaw** [dzenbot/DZNEmptyDataSet#47]
Hi, here's  curly one.

It appears that if you insert the empty view beneath the UITableViewWrapperView in the tableview's hierarchy, gestures don't work in iOS7. 

Normally it's fine, since inserting the empty view at index 1 puts it above this view (UITableViewWrapperView view is usually at index 0)

But if you've set a background view for your tableview, the background view is at index 0 and the UITableViewWrapperView is at index 1. Thus the empty view is inserted beneath the UITableViewWrapperView view.

This is only a problem in iOS7. In iOS8 inserting the empty view beneath the UITableViewWrapperView view doesn't seem to matter, gestures still work.

Here's my solution:

```
if ([self isKindOfClass:[UITableView class]] && self.subviews.count > 1) {
    UITableView *tableview = (UITableView *)self;
    if (tableview.backgroundView && self.subviews.count > 2) {
       [tableview insertSubview:view atIndex:2];
   } else {
       [tableview insertSubview:view atIndex:1];
   }
}
```

I can submit a pull request if you think the above is not crazy.

**Comment by bartvandendriessche** [comment]
Tried to update one of my apps to the latest version of DZNEmptyDataSet today, and still ran into this issue with the latest :head pod.

I dug in a bit more, and came up with a simpler fix. 

Basically, the problem is that UITableViewWrapperView doesn't allow touches to pass through on iOS 7, but that's something we can change when adding the `emptyDataSetView` to the hierarchy.

In `dzn_reloadEmptyDataSet` do the following:

```objc
// snip
        DZNEmptyDataSetView *view = self.emptyDataSetView;
        
        if (!view.superview) {
            // Send the view all the way to the back, in case a header and/or footer is present, as well as for sectionHeaders or any other content
            if (([self isKindOfClass:[UITableView class]] || [self isKindOfClass:[UICollectionView class]]) && self.subviews.count > 1) {
                [self disableUserInteractionOfUITableWrapperViewIfNecessary];
                [self insertSubview:view atIndex:0];
            }
            else {
                [self addSubview:view];
            }
        }
// snip
```

And then implement `disableUserInteractionOfUITableWrapperViewIfNecessary` as follows:

```objc
- (void)disableUserInteractionOfUITableWrapperViewIfNecessary
{
    if (floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_6_1 &&
        floor(NSFoundationVersionNumber) <= NSFoundationVersionNumber_iOS_7_1 &&
        [self isKindOfClass:[UITableView class]]) {
        for (UIView *subview in [self subviews]) {
            if ([subview isKindOfClass:NSClassFromString(@"UITableViewWrapperView")]) {
                subview.userInteractionEnabled = NO;
            }
        }
    }
}
```
