### ISSUE TITLE
滚动一段距离y,再刷新,刚好数据为空,这时占位图也会偏移y,解决方法如下:

### ISSUE THREAD

**Issue by zj381652512** [dzenbot/DZNEmptyDataSet#473]
- (void)dzn_didAppear
{
    if (self.emptyDataSetDelegate && [self.emptyDataSetDelegate respondsToSelector:@selector(emptyDataSetDidAppear:)]) {
        [self.emptyDataSetDelegate emptyDataSetDidAppear:self];
    }
    // add by zj: 解决滚动位置被还原后,占位图位置未及时更新问题
    dispatch_async(dispatch_get_main_queue(), ^{
        self.emptyDataSetView.frame = self.bounds;
    });
}

**Comment by luotao001** [comment]
有用,可以解决问题。
That works!

**Comment by huangrun** [comment]
不修改源码的解决方法：
- (void)emptyDataSetDidAppear:(UIScrollView *)scrollView {
    UIView *emptyView = [scrollView valueForKey:@"emptyDataSetView"];
    CGRect frame = emptyView.frame;
    frame.origin.y = 0;
    emptyView.frame = frame;
}
