### ISSUE TITLE
Crash on device running iOS7

### ISSUE THREAD

**Issue by tranngoclinh88** [dzenbot/DZNEmptyDataSet#96]
After update framework to version 1.6, my application crashes.
The reason:

[__NSCFString containsString:]: unrecognized selector sent to instance ...

in method *dzn_original_implementation*

**Comment by mariovillamizar** [comment]
Yes, I get the same error. Please, solve this issue and update again.

**Comment by mythodeia** [comment]
read this https://github.com/dzenbot/DZNEmptyDataSet#dealloc
you do not need to dealloc any more
